### ISSUE TITLE
Issue with Python after loading anaconda3

### ISSUE THREAD

**Issue by TheChesireCat** [northeastern-rc/rc-public-documentation#9]
I was following https://rc-docs.northeastern.edu/en/latest/using-discovery/workingwithgpu.html

After loading anaconda, the default python after creating and activating a conda environment remains /shared/centos7/anaconda3/2021.11/bin/python and not <path_to_conda_env>/bin/python3 resulting in a : ModuleNotFoundError: No module named 'torch'

I was able to fix this once I switched to calling python with "<path_to_env>/bin/python" instead of just python.

**Comment by marianalevineu** [comment]
Hi @TheChesireCat m I wasn't able to reproduce the error you're reporting. I followed these instructions:
`srun -p gpu -N 1 -n 10 --pty --gres=gpu:1 /bin/bash
module load cuda/11.1
module load anaconda3/2021.11
conda create --name pytorch_env python=3.7 -y
source activate pytorch_env
which python
~/.conda/envs/pytorch_env/bin/python`
Maybe you can try running `conda activate pytorch_env` instead?
Could you also make sure you're not loading any additional conda environments in your ~/.bashrc ?
If you're still facing issues, please also open a service ticket so we can have a closer look at your environment: https://bit.ly/NURC-Assistance
Thanks,
Mariana.

**Comment by TheChesireCat** [comment]
Thank you.

**Comment by TheChesireCat** [comment]
The issue for me right now seems to be the PATH string 

`/shared/centos7/anaconda3/2021.11/sbin:/shared/centos7/anaconda3/2021.11/bin:/shared/centos7/cuda/11.1/bin:/home/username/.conda/envs/pytorch_env/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/dell/srvadmin/sbin`

Which looks for python first in the shared path then the conda_env

**Comment by marianalevineu** [comment]
We'll probably need to have a closer look at your environment on the cluster since the issue is not reproducible on my end. The $PATH variable should be updated once you activate your environment. Here's what should happen when you `source activate pytorch_env`: <br/>
`echo $PATH`<br/>
`/home/username/.conda/envs/pytorch_env/bin:/shared/centos7/anaconda3/2021.11/condabin:...` <br/>
So it looks like your PATH variable didn't get updated in the right order for some reason, or that you had it "source activate" first and then loaded the modules. 
I would also suggest to try clearing your ~/.conda directory (or backing it up to a different directory), clearing .condarc (or backing up), clearing your ~/.bashrc file (or backing up) to its generic form (make sure to use the regular BASH shell setup https://rc-docs.northeastern.edu/en/latest/using-discovery/bashrc.html?highlight=bashrc) and try again. <br/>
If you're still able to reproduce the issue given the generic Discovery environment please raise a ticket with RC for further investigation.
Thanks,
Mariana.
